# Generated by Django 5.1.6 on 2025-02-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="description",
            field=models.TextField(default="lorem ipsum"),
            preserve_default=False,
        ),
    ]
